### ISSUE TITLE
Upgrade to v1.42 API version

### ISSUE THREAD

**Issue by vv9k** [vv9k/docker-api-rs#49]
- [x] POST /containers/{id}/stop and POST /containers/{id}/restart now accept a signal query parameter, which allows overriding the container’s default stop- signal.
 - [x] GET /images/json now accepts query parameter shared-size. When set true, images returned will include SharedSize, which provides the size on disk shared with other images present on the system.
 - [x] GET /system/df now accepts query parameter type. When set, computes and returns data only for the specified object type. The parameter can be specified multiple times to select several object types. Supported values are: container, image, volume, build-cache.
 - [x] GET /_ping and HEAD /_ping now return Builder-Version by default. This header contains the default builder to use, and is a recommendation as advertised by the daemon. However, it is up to the client to choose which builder to use.
 - [x] POST /volumes/create now accepts a new ClusterVolumeSpec to create a cluster volume (CNI). This option can only be used if the daemon is a Swarm manager. The Volume response on creation now also can contain a ClusterVolume field with information about the created volume.
 - [x] Added a new PUT /volumes{name} endpoint to update cluster volumes (CNI). Cluster volumes are only supported if the daemon is a Swarm manager.
 - [x] GET /containers/{name}/attach/ws endpoint now accepts stdin, stdout and stderr query parameters to only attach to configured streams.
       NOTE: These parameters were documented before in older API versions, but not actually supported. API versions before v1.42 continue to ignore these parameters and default to attaching to all streams. To preserve the pre-v1.42 behavior, set all three query parameters (?stdin=1,stdout=1,stderr=1).
 - [x] POST /containers/{id}/exec now accepts an optional ConsoleSize parameter. It allows to set the console size of the executed process immediately when it’s created.

**Comment by astrolemonade** [comment]
For some reason it does not work with the v1.42 API version
```rust
use docker_api::{opts::ContainerListOpts, Docker};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let docker = Docker::unix("/var/run/docker.sock");
    let opts = ContainerListOpts::builder().all(true).build();
    let containers = docker.containers().list(&opts).await?;
    for cont in containers {
        println!("{}", cont.created.unwrap());
    }
    Ok(())
}
```

```toml
[package]
name = "exps"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docker-api = "0.13.0"
tokio = { version = "1.27.0", features = ["full"] }
```

```bash
$ docker --version
Docker version 20.10.22, build 42c8b314993e5eb3cc2776da0bbe41d5eb4b707b
```

**Comment by astrolemonade** [comment]
@vv9k

**Comment by vv9k** [comment]
@astrolemonade  Could you perhaps post the error that you're getting as a separate issue? We can then consider how to try to make it work with older versions ;)
